# Generated by Django 5.2.6 on 2025-09-10 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="completion_date",
            field=models.DateField(verbose_name="Date d'achèvement"),
        ),
        migrations.AlterField(
            model_name="project",
            name="demo_url",
            field=models.URLField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="Lien de démonstration",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="github_url",
            field=models.URLField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="Lien GitHub",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                upload_to="projects/", verbose_name="Image du projet"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.CharField(
                help_text="Séparer par des virgules",
                max_length=300,
                verbose_name="Technologies utilisées",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(
                help_text="Ex: fas fa-laptop-code",
                max_length=50,
                verbose_name="Icône FontAwesome",
            ),
        ),
    ]
